apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-curler
  namespace: default
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io